var mongoose    = require("mongoose");
var Campground  = require("./models/campground");
var Comment     = require("./models/comment");

var data = [
        {name: "Panther Crossing", image: "https://source.unsplash.com/jl2T_E4tUyo/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Scruntal Bluffs", image: "https://source.unsplash.com/gcCcIy6Fc_M/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Meedly Weavels", image: "https://source.unsplash.com/tRGwX1HcTd4/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Awesome Possums", image: "https://source.unsplash.com/SId-lmFXSDU/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Serpent Cove", image: "https://source.unsplash.com/sK1hW5knKkw/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Happy Lemurs", image: "https://source.unsplash.com/WWb4gn130JI/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Gerbil Run", image: "https://source.unsplash.com/WWb4gn130JI/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Scruntal Bluffs", image: "https://source.unsplash.com/gcCcIy6Fc_M/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Meedly Weavels", image: "https://source.unsplash.com/tRGwX1HcTd4/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Awesome Possums", image: "https://source.unsplash.com/SId-lmFXSDU/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Serpent Cove", image: "https://source.unsplash.com/sK1hW5knKkw/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Happy Lemurs", image: "https://source.unsplash.com/WWb4gn130JI/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."},
        {name: "Gerbil Run", image: "https://source.unsplash.com/WWb4gn130JI/480x288", desc: "Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Animi, id est laborum et dolorum fuga. Ut enim ad minim veniam, quis nostrud exercitation ullamco. Corrupti quos dolores et quas molestias excepturi sint occaecati. Nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam. Esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. At vero eos et accusamus. At vero eos et accusamus. Sed ut perspiciatis unde omnis iste natus error sit voluptatem. Architecto beatae vitae dicta sunt explicabo. Itaque earum rerum hic tenetur a sapiente delectus."}
];

function seedDB() {
    //Remove ALL campgrounds
    Campground.remove({}, function (err){
        if(err) {
            console.log(err);
        } else {
            console.log("removing ALL campgrounds | seeding fresh campgrounds & comments...");
            console.log("gogogo!!");
                //Add some campgrounds
            data.forEach(function(seed) {
                Campground.create(seed, function(err, campground) {
                    if (err) {
                        console.log(err);
                    } else {
                        // create a comment
                        Comment.create({text: "this place is rad, bruh...",
                            author: "Illiad"
                        }, function(err, comment) {
                            if (err) {
                                console.log(err);
                            } else {
                                campground.comments.push(comment);
                                campground.save();
                            }
                        });
                    }
                });
            });
        }
    });
}

module.exports = seedDB;